#!/usr/bin/env node
// @ts-check
/**
 * Ordito guard step for the node-ts stack. Generated by `ordito init`; part of the locked
 * contract, so it must never be edited by hand.
 *
 * Run from the project root. Exit codes:
 *   0  the contract is intact and no forbidden marker was introduced
 *   1  contract violation (changed, missing or extra locked file, forbidden marker)
 *   2  environment problem (corrupt lock, git unavailable when the lock needs it)
 *
 * Lock format: see ADR 0007 in the Ordito repository.
 */
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, lstatSync, readdirSync, readFileSync } from "node:fs";

const LOCK_PATH = ".ordito/lock.json";
const SOURCE_FILE = /\.(?:[cm]?[jt]s|[jt]sx)$/;
const SKIPPED_DIRS = new Set(["node_modules", "dist", ".ordito", ".git", ".jj"]);
/** @type {Array<[string, RegExp]>} */
const MARKERS = [
  [".only(", /\.only\(/],
  [".skip(", /\.skip\(/],
  [".todo(", /\.todo\(/],
  ["@ts-ignore", /@ts-ignore/],
  ["@ts-nocheck", /@ts-nocheck/],
  ["@ts-expect-error", /@ts-expect-error/],
  ["as any", /\bas\s+any\b/],
  ["eslint-disable", /eslint-disable/],
  ["biome-ignore", /biome-ignore/],
  ["oxlint-disable", /oxlint-disable/],
];

class EnvironmentError extends Error {}

/**
 * @typedef {{ ordito: string, lockedAt: string, base: string | null, dirs: string[], files: Record<string, string> }} Lock
 * @typedef {{ path: string, line: number | null, message: string }} Violation
 */

/** @returns {Lock | null} */
function readLock() {
  if (!existsSync(LOCK_PATH)) return null;
  /** @type {unknown} */
  let data;
  try {
    data = JSON.parse(readFileSync(LOCK_PATH, "utf8"));
  } catch (err) {
    throw new EnvironmentError(`${LOCK_PATH} is not valid JSON: ${String(err)}`);
  }
  if (!isLock(data)) throw new EnvironmentError(`${LOCK_PATH} does not match the lock format`);
  return data;
}

/**
 * @param {unknown} value
 * @returns {value is Lock}
 */
function isLock(value) {
  if (typeof value !== "object" || value === null) return false;
  const lock = /** @type {Record<string, unknown>} */ (value);
  const files = lock.files;
  return (
    typeof lock.ordito === "string" &&
    (lock.base === null || typeof lock.base === "string") &&
    Array.isArray(lock.dirs) &&
    lock.dirs.every((d) => typeof d === "string") &&
    typeof files === "object" &&
    files !== null &&
    Object.values(files).every((h) => typeof h === "string" && /^[0-9a-f]{64}$/.test(h))
  );
}

/** @param {string} path */
function sha256(path) {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}

/**
 * Lists files under `dir` recursively, as POSIX paths relative to the project root.
 * @param {string} dir
 * @param {(name: string) => boolean} skipDir
 * @returns {string[]}
 */
function walk(dir, skipDir) {
  if (!existsSync(dir)) return [];
  /** @type {string[]} */
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = dir === "." ? entry.name : `${dir}/${entry.name}`;
    if (entry.isDirectory()) {
      if (!skipDir(entry.name)) out.push(...walk(path, skipDir));
    } else if (entry.isFile() || entry.isSymbolicLink()) {
      out.push(path);
    }
  }
  return out;
}

/**
 * @param {Lock} lock
 * @returns {Violation[]}
 */
function checkDigests(lock) {
  /** @type {Violation[]} */
  const violations = [];
  for (const [path, digest] of Object.entries(lock.files)) {
    if (!existsSync(path) || !lstatSync(path).isFile()) {
      violations.push({ path, line: null, message: "locked file is missing" });
    } else if (sha256(path) !== digest) {
      violations.push({ path, line: null, message: "locked file was modified" });
    }
  }
  for (const dir of lock.dirs) {
    for (const path of walk(dir, () => false)) {
      if (!(path in lock.files)) {
        violations.push({ path, line: null, message: `file added to locked directory ${dir}` });
      }
    }
  }
  return violations;
}

/**
 * @param {string[]} args
 * @returns {string}
 */
function git(args) {
  try {
    return execFileSync("git", ["-c", "core.quotePath=false", ...args], {
      encoding: "utf8",
      maxBuffer: 256 * 1024 * 1024,
      stdio: ["ignore", "pipe", "pipe"],
    });
  } catch (err) {
    throw new EnvironmentError(`git ${args.join(" ")} failed: ${String(err)}`);
  }
}

/**
 * Lines added since `base`: tracked changes from `git diff`, plus every line of untracked
 * files (an agent may never stage what it writes).
 * @param {string} base
 * @returns {Map<string, Array<[number, string]>>}
 */
function addedLines(base) {
  /** @type {Map<string, Array<[number, string]>>} */
  const added = new Map();
  /** @type {string | null} */
  let file = null;
  let line = 0;
  for (const text of git(["diff", "--no-color", "--no-ext-diff", "--unified=0", base, "--"]).split(
    "\n",
  )) {
    if (text.startsWith("+++ ")) {
      const target = text.slice(4);
      file = target === "/dev/null" ? null : target.replace(/^"?b\//, "").replace(/"$/, "");
      continue;
    }
    const hunk = /^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@/.exec(text);
    if (hunk) {
      line = Number(hunk[1]);
      continue;
    }
    if (file !== null && text.startsWith("+")) {
      const lines = added.get(file) ?? [];
      lines.push([line, text.slice(1)]);
      added.set(file, lines);
      line++;
    }
  }
  for (const path of git(["ls-files", "--others", "--exclude-standard", "-z"]).split("\0")) {
    if (path !== "" && !added.has(path) && existsSync(path) && lstatSync(path).isFile()) {
      added.set(path, numbered(readFileSync(path, "utf8")));
    }
  }
  return added;
}

/**
 * @param {string} content
 * @returns {Array<[number, string]>}
 */
function numbered(content) {
  return content.split("\n").map((text, i) => [i + 1, text]);
}

/**
 * @param {string} path
 */
function isScanned(path) {
  return SOURCE_FILE.test(path) && !path.split("/").some((part) => SKIPPED_DIRS.has(part));
}

/**
 * @param {Map<string, Array<[number, string]>>} lines
 * @returns {Violation[]}
 */
function scanMarkers(lines) {
  /** @type {Violation[]} */
  const violations = [];
  for (const [path, rows] of lines) {
    if (!isScanned(path)) continue;
    for (const [line, text] of rows) {
      for (const [name, pattern] of MARKERS) {
        if (pattern.test(text)) {
          violations.push({ path, line, message: `forbidden marker "${name}"` });
        }
      }
    }
  }
  return violations;
}

/** @returns {Map<string, Array<[number, string]>>} */
function allSourceLines() {
  /** @type {Map<string, Array<[number, string]>>} */
  const lines = new Map();
  for (const path of walk(".", (name) => SKIPPED_DIRS.has(name))) {
    if (isScanned(path)) lines.set(path, numbered(readFileSync(path, "utf8")));
  }
  return lines;
}

function main() {
  const lock = readLock();
  const violations = lock === null ? [] : checkDigests(lock);
  violations.push(...scanMarkers(lock?.base ? addedLines(lock.base) : allSourceLines()));

  if (lock === null) console.log("guard: no lock yet, contract digests not checked");
  if (violations.length === 0) {
    console.log("guard: ok");
    return 0;
  }
  for (const v of violations) {
    console.log(`${v.path}${v.line === null ? "" : `:${v.line}`}: ${v.message}`);
  }
  console.log(`guard: ${violations.length} violation(s)`);
  return 1;
}

try {
  process.exitCode = main();
} catch (err) {
  // Any unexpected failure is reported as an environment problem: exiting 1 would tell the
  // agent its code is wrong when the guard itself could not run.
  console.log(
    `guard: ${err instanceof EnvironmentError ? err.message : `internal error: ${err instanceof Error ? (err.stack ?? err.message) : String(err)}`}`,
  );
  process.exitCode = 2;
}
