#!/usr/bin/env bash
# Themis verifier for the node-ts stack. Generated by `themis init`.
# Part of the locked contract: regenerate it with `themis init --force`, never edit it by hand.
#
# Usage:      .themis/verify.sh [AC-<n> ...]
#             With criterion ids, acceptance runs only those criteria: the task under work plus
#             the tasks already done (a criterion not implemented yet must not fail the task).
#             Without ids, every criterion runs. `none` runs no criterion (for a task that owns
#             none, such as setup, before any criterion is done).
# Exit codes: 0 pass, 1 the code is wrong, 2 the environment is broken.
# On failure .verify.log holds the failed step and the tail of its output, without ANSI codes.

set -uo pipefail

# Steps enabled by the spec frontmatter (`verify:`). The guard step always runs.
STEPS="__THEMIS_STEPS__"
LOG_LINES="${THEMIS_LOG_LINES:-200}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)" || exit 2
cd "$ROOT" || exit 2
LOG="$ROOT/.verify.log"
BIN="$ROOT/node_modules/.bin"
TASK_IDS=("$@")

export NO_COLOR=1 FORCE_COLOR=0 CI=1

OUTPUT="$(mktemp "${TMPDIR:-/tmp}/themis-verify.XXXXXX")" || exit 2
trap 'rm -f "$OUTPUT"' EXIT
rm -f "$LOG"

enabled() {
  case " $STEPS " in
    *" $1 "*) return 0 ;;
    *) return 1 ;;
  esac
}

# fail <step> <exit code> <command> [message]: writes .verify.log and exits.
fail() {
  local step="$1" code="$2" command="$3" message="${4:-}"
  {
    printf 'step: %s\nexit: %s\ncommand: %s\n' "$step" "$code" "$command"
    if [ -n "$message" ]; then printf 'message: %s\n' "$message"; fi
    if [ -s "$OUTPUT" ]; then
      printf -- '--- last %s lines of output ---\n' "$LOG_LINES"
      tail -n "$LOG_LINES" "$OUTPUT" | sed $'s/\x1b\\[[0-9;?]*[ -/]*[@-~]//g'
    fi
  } >"$LOG"
  echo "verify: FAIL at $step (exit $code), see .verify.log" >&2
  exit "$code"
}

# run <step> <exit code on failure|passthrough> <command...>
# A command that cannot be executed (126/127) is always an environment problem.
# `passthrough` keeps the command's own 1 or 2 (used by the guard).
run() {
  local step="$1" code="$2"
  shift 2
  echo "verify: $step" >&2
  "$@" >"$OUTPUT" 2>&1
  local status=$?
  if [ "$status" -eq 0 ]; then return 0; fi
  if [ "$status" -eq 126 ] || [ "$status" -eq 127 ]; then
    fail "$step" 2 "$*" "command could not be executed"
  fi
  if [ "$code" = "passthrough" ]; then
    if [ "$status" -eq 1 ]; then code=1; else code=2; fi
  fi
  fail "$step" "$code" "$*"
}

# abort: like fail, for checks that ran no command, so no stale output reaches the log.
abort() {
  : >"$OUTPUT"
  fail "$@"
}

require_bin() {
  if [ ! -x "$BIN/$2" ]; then
    abort "$1" 2 "$BIN/$2" "$2 is not installed; run npm install"
  fi
}

# --- preflight -------------------------------------------------------------------------------
if [ "${#TASK_IDS[@]}" -eq 1 ] && [ "${TASK_IDS[0]}" = "none" ]; then
  TASK_IDS=()
  NO_CRITERIA=1
else
  NO_CRITERIA=0
fi
for id in "${TASK_IDS[@]+"${TASK_IDS[@]}"}"; do
  if [[ ! "$id" =~ ^AC-[1-9][0-9]*$ ]]; then
    abort preflight 2 "verify.sh $*" "invalid criterion id \"$id\", expected AC-<n>"
  fi
done
command -v node >/dev/null 2>&1 || abort preflight 2 node "node is not on PATH"
[ -d node_modules ] || abort preflight 2 "npm install" "node_modules is missing; run npm install"

# --- guard -----------------------------------------------------------------------------------
run guard passthrough node .themis/guard.mjs

# --- static checks ---------------------------------------------------------------------------
if enabled typecheck; then
  require_bin typecheck tsc
  run typecheck 1 "$BIN/tsc" --noEmit
fi

if enabled lint; then
  require_bin lint biome
  run lint 1 "$BIN/biome" check .
fi

if enabled unit; then
  require_bin unit vitest
  run unit 1 "$BIN/vitest" run --exclude 'tests/acceptance/**' --passWithNoTests --retry=0
fi

# --- infrastructure --------------------------------------------------------------------------
if enabled infra; then
  compose=""
  for candidate in compose.yaml compose.yml docker-compose.yaml docker-compose.yml; do
    if [ -f "$candidate" ]; then
      compose="$candidate"
      break
    fi
  done
  # The compose file is part of the implementation, so its absence is a code problem.
  [ -n "$compose" ] || abort infra 1 "docker compose" "infra is enabled but there is no compose file"
  run infra 2 docker info
  run infra 1 docker compose -f "$compose" config -q
  run infra 2 docker compose -f "$compose" up -d --wait
fi

if enabled migrate; then
  if ! node -e 'const p = JSON.parse(require("fs").readFileSync("package.json", "utf8")); process.exit(p.scripts && p.scripts.migrate ? 0 : 1)' >"$OUTPUT" 2>&1; then
    fail migrate 1 "npm run migrate" "package.json has no \"migrate\" script"
  fi
  run migrate 1 npm run --silent migrate
fi

# --- acceptance ------------------------------------------------------------------------------
if enabled acceptance; then
  if [ ! -f .themis/lock.json ]; then
    abort acceptance 2 "themis approve tests" "contract not locked: run themis approve tests"
  fi
  require_bin acceptance vitest
  if [ "$NO_CRITERIA" -eq 1 ]; then
    : # No criterion selected: the contract is still required to be locked (checked above).
  elif [ "${#TASK_IDS[@]}" -gt 0 ]; then
    pattern="$(IFS='|'; echo "${TASK_IDS[*]}")"
    run "acceptance ${TASK_IDS[*]}" 1 "$BIN/vitest" run tests/acceptance --retry=0 -t "^($pattern):"
  else
    run acceptance 1 "$BIN/vitest" run tests/acceptance --retry=0
  fi
fi

rm -f "$LOG"
echo "verify: PASS" >&2
exit 0
