import { existsSync } from "node:fs";
import { defineConfig } from "vitest/config";

// Generated by `themis init`; part of the locked contract.
// The acceptance harness may provide a global setup (e.g. to start infrastructure) without
// editing this file: it is picked up only if it exists.
const ACCEPTANCE_SETUP = "tests/acceptance/global-setup.ts";

export default defineConfig({
  test: {
    projects: [
      {
        extends: true,
        test: {
          name: "unit",
          include: ["src/**/*.test.ts", "tests/**/*.test.ts"],
          exclude: ["tests/acceptance/**", "**/node_modules/**"],
        },
      },
      {
        extends: true,
        test: {
          name: "acceptance",
          include: ["tests/acceptance/**/*.test.ts"],
          // Acceptance files share external state such as a database.
          fileParallelism: false,
          testTimeout: 30_000,
          hookTimeout: 60_000,
          globalSetup: existsSync(ACCEPTANCE_SETUP) ? [ACCEPTANCE_SETUP] : [],
        },
      },
    ],
  },
});
